services:
  db:
    image: postgres:11.15-bullseye
    command: postgres -c 'max_connections=200'
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./src/main/resources/db/pginit.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: therapy_room_db
    networks:
      - therapy-cabinet-network
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 2048M
        reservations:
          cpus: '0.1'
          memory: 1536M
  cache:
    image: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

networks:
  therapy-cabinet-network:
    driver: bridge
volumes:
  postgres-data:
    external: false