spring:
  application:
    name: therapy-room
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active: local
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
mybatis:
  config-location: classpath:mybatis/conf.xml
server:
  servlet:
    context-path: /therapy_room
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /swagger.json
