spring:
  application:
    name: therapy-room
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active: local
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
