spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/therapy_room_db
    username: postgres
    password: secret
    hikari:
      schema: doc
  liquibase:
    default-schema: doc
    enabled: true
  redis:
    port: 6379
    password: secret
    host: localhost
