spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/therapy_room_db
    username: postgres
    password: secret
    hikari:
      schema: doc
  liquibase:
    default-schema: doc
    enabled: true
