spring:
  datasource:
    url: jdbc:mysql://std-mysql.ist.mospolytech.ru:3306/std_1305_therapy?serverTimezone=UTC
    username: std_1305_therapy
    password: test1324
    hikari:
      schema: std_1305_therapy
  liquibase:
    default-schema: std_1305_therapy
    enabled: false
  redis:
    port: 6379
    password: secret
    host: localhost
