spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doc
    username: mysql
    password: secret
    hikari:
      schema: doc
  liquibase:
    default-schema: doc
    enabled: true
  redis:
    port: 6379
    password: secret
    host: localhost
